### ISSUE TITLE
如何实现scroll滚动加载呢，请教一下

### ISSUE THREAD

**Issue by ycrqwq** [AwesomeDevin/vue-waterfall2#27]

**Comment by AwesomeDevin** [comment]
组件提供的loadmore事件无法监听容器滚动，监听的是window的滚动事件
没监听到的情况有两种可能

1.内容高度不够
2.滚动的是父容器，所以没有触发
举个简单的demo
```css
html{
    overflow: auto;
    height: 100vh;
}
```
这样的话滚动的是html，不是winodw，loadmore事件会失效
